const hOpts=(a,w)=>{let r=[a,...w].map(String).filter((x,i,z)=>z.indexOf(x)===i);for(const f of ['Güvenilir bir yetişkinden yardım isterim.','Sakin kalıp güvenli davranırım.','Kurala uygun hareket ederim.','Durumu açıkça anlatırım.'])if(r.length<4&&!r.includes(f))r.push(f);return r.slice(0,4)},hQ=(p,v,a,w)=>[p,v,a,hOpts(a,w)];
const times=['Sabah','Okuldayken','Öğle arasında','Okuldan sonra'];
const healthActs=['kahvaltı yapmak','su içmek','sebze ve meyve tüketmek','dişleri fırçalamak','elleri yıkamak','zamanında uyumak','hareket etmek','temiz kıyafet giymek','tırnakları temiz tutmak','öğünleri düzenli yemek','ekran süresini sınırlamak','açık havada oynamak','kişisel bakım yapmak','dinlenmek','süt veya yoğurt tüketmek','yiyecekleri temiz tüketmek','spor sonrası su içmek','öksürürken ağzı kapatmak','havlu gibi kişisel eşyaları paylaşmamak','çöpleri kutuya atmak','odanın havasını yenilemek','aşırı şekerden kaçınmak','beslenme çantasını temiz tutmak','dik oturmak','güne dengeli başlamak'];
const health=Array.from({length:100},(_,i)=>{let a=healthActs[i%25],t=times[Math.floor(i/25)],k=Math.floor(i/25);if(k===0)return hQ(t+' sağlıklı büyümeyi desteklemek için “'+a+'” neden önemlidir?','🌱 Sağlıklı büyüme','Bedenimizin sağlıklı çalışmasına yardım eder.',['Sağlığımızı olumsuz etkiler.','Yalnızca zaman kaybettirir.','Hiçbir yararı yoktur.']);if(k===1)return hQ(t+' “'+a+'” alışkanlığını düzenli sürdürmek için ne yapılmalıdır?','✅ Sağlıklı alışkanlık','Günlük plan içinde buna zaman ayrılmalıdır.',['Sürekli ertelenmelidir.','Yalnız hastayken yapılmalıdır.','Tamamen bırakılmalıdır.']);if(k===2)return hQ(t+' “'+a+'” ihmal edilirse hangi davranış daha doğru olur?','🔄 Sağlıklı seçim','Eksik alışkanlığı fark edip yeniden uygulamaya başlarım.',['İhmal etmeyi sürdürürüm.','Sağlıksız seçimi artırırım.','Kimseye danışmam.']);return hQ(t+' sağlıklı bir gün planlanıyor. “'+a+'” bu planda nasıl yer almalıdır?','🗓️ Dengeli yaşam','Diğer sağlıklı alışkanlıklarla dengeli biçimde yer almalıdır.',['Bütün günün tek etkinliği olmalıdır.','Uyku ve beslenmenin yerine geçmelidir.','Plana hiç alınmamalıdır.'])});
const spaceSituations=['Bir arkadaşın sana çok yaklaştı','Birisi izinsiz sarılmak istedi','Arkadaşın çantanı açtı','Bir kişi saçına dokundu','Sırada biri seni itti','Tanımadığın biri elini tutmak istedi','Arkadaşın fotoğrafını çekmek istedi','Birisi özel eşyalarını karıştırdı','Oyunda istemediğin bir dokunuş oldu','Bir kişi odana izinsiz girdi','Arkadaşın telefonunu almak istedi','Birisi sırrını söylemen için baskı yaptı','Tanımadığın biri seni çağırdı','Arkadaşın kalemini izinsiz aldı','Bir kişi istemediğin şakayı sürdürdü','Biri seni rahatsız eden sözler söyledi','Arkadaşın oturduğun yere çok yaklaştı','Birisi kişisel bilgini sordu','Tanımadığın biri hediye teklif etti','Bir kişi yalnız kalmanızı istedi','Arkadaşın “hayır” cevabını dinlemedi','Biri seni korkutan bir davranış yaptı','Bir kişi rahatsızlığını gizlemeni söyledi','Kalabalıkta kendini güvensiz hissettin','Bir yetişkinin davranışı seni rahatsız etti'];
const space=Array.from({length:100},(_,i)=>{let s=spaceSituations[i%25],k=Math.floor(i/25);if(k===0)return hQ(s+'. Kişisel alanını korumak için ilk olarak ne söylemelisin?','🛡️ Kişisel sınır','“Hayır, bunu istemiyorum.” demeliyim.',['Sessiz kalmalıyım.','İstemediğim hâlde kabul etmeliyim.','Durumu gizlemeliyim.']);if(k===1)return hQ(s+'. Rahatsızlık devam ederse ne yapmalısın?','🚶 Güvenli uzaklaşma','Oradan uzaklaşıp güvenilir bir yetişkine anlatmalıyım.',['Tek başıma çözmeye çalışmalıyım.','Kimseye söylememeliyim.','Aynı davranışla karşılık vermeliyim.']);if(k===2)return hQ(s+'. Bu durumda izin ve sınırlarla ilgili hangi kural geçerlidir?','✋ İzin isteme','Herkes başkasının kişisel alanına girmeden önce izin istemelidir.',['Arkadaşlar izin istemek zorunda değildir.','Rahatsızlık önemli değildir.','Büyükler her davranışı yapabilir.']);return hQ(s+'. Güvenilir yetişkine anlatırken nasıl konuşmalısın?','🗣️ Yardım isteme','Ne olduğunu açık ve doğru biçimde anlatmalıyım.',['Olayı saklamalıyım.','Kendimi suçlamalıyım.','Yanlış bilgi vermeliyim.'])});
const trafficItems=[['🚸','Okul geçidi'],['🚶','Yaya geçidi'],['🛑','Dur'],['🚦','Trafik ışıkları'],['🚲','Bisiklet yolu'],['⛔','Giriş yasaktır'],['⚠️','Dikkat'],['🚧','Yol çalışması'],['🅿️','Park yeri'],['♿','Erişilebilir alan'],['🚫🚲','Bisiklet giremez'],['🚫🚶','Yaya giremez'],['⬅️','Sola yön'],['➡️','Sağa yön'],['↩️','Dönüş yönü'],['🏥','Hastane'],['🚏','Otobüs durağı'],['🚂','Demir yolu geçidi'],['🐄','Hayvan çıkabilir'],['🌉','Dar köprü'],['30','Hız sınırı'],['🔺','Uyarı levhası'],['⭕','Yasaklama levhası'],['🔵','Bilgi levhası'],['🦺','Görünürlük ve güvenlik']];
const traffic=Array.from({length:100},(_,i)=>{let z=trafficItems[i%25],k=Math.floor(i/25);if(k===0)return hQ(z[0]+' işaretinin anlamı hangisidir?','🪧 Trafik işareti',z[1],[trafficItems[(i+3)%25][1],trafficItems[(i+7)%25][1],trafficItems[(i+11)%25][1]]);if(k===1)return hQ(z[1]+' işaretini gördüğünde yaya olarak ne yapmalısın?','🚦 Güvenli yaya','İşaretin bildirdiği kurala dikkat etmeliyim.',['İşareti görmezden gelmeliyim.','Yola koşarak çıkmalıyım.','Park etmiş araçların arasından geçmeliyim.']);if(k===2)return hQ(z[1]+' işareti trafik için neden önemlidir?','🛣️ Trafik düzeni','Yol kullanıcılarını bilgilendirerek güvenliği destekler.',['Yalnızca yolu süsler.','Kuralları gereksiz hâle getirir.','Yayaların dikkatini dağıtır.']);return hQ(z[1]+' bulunan bir yolda en güvenli davranış hangisidir?','👀 İşareti fark et','İşaretin anlamına uygun ve dikkatli davranmaktır.',['İşaretin tersini yapmaktır.','Çevreyi kontrol etmeden ilerlemektir.','Başkalarını tehlikeye atmaktır.'])});
const emergencies=['Evde yangın çıktı','Bir kişi bayıldı','Trafik kazası gördün','Deprem sırasında sarsıntı başladı','Gaz kokusu fark ettin','Bir arkadaşın ciddi biçimde yaralandı','Sel suyu yükseliyor','Ormanda duman gördün','Bir çocuk kayboldu','Elektrik kablosu koptu','Asansörde kaldın','Bir kişi nefes almakta zorlanıyor','Okulda alarm çaldı','Şiddetli fırtına başladı','Bir yabancı yardım bahanesiyle yaklaştı','Bir ilaç yanlışlıkla içildi','Keskin bir cisimle yaralanma oldu','Suda boğulma tehlikesi gördün','Bir bina hasar gördü','Toprak kayması belirtisi fark ettin','Sokakta tehlikeli bir hayvan var','Bir arkadaşın zehirlendiğini düşünüyorsun','Yoğun duman olan bir oda gördün','Acil çıkış yolu kapandı','Kalabalıkta ailenden ayrıldın'];
const emergency=Array.from({length:100},(_,i)=>{let s=emergencies[i%25],k=Math.floor(i/25);if(k===0)return hQ(s+'. İlk güvenli davranış hangisidir?','🚨 Acil durum','Kendimi tehlikeden uzaklaştırıp bir yetişkine haber veririm.',['Tehlikeye yaklaşırım.','Olayı oyun sanarım.','Kimseye söylemem.']);if(k===1)return hQ(s+'. Acil yardım gerekiyorsa hangi numara aranmalıdır?','📞 Türkiye acil çağrı','112',['110','155','118']);if(k===2)return hQ(s+'. 112 görevlisine hangi bilgi doğru biçimde verilmelidir?','🗣️ Acil durum bildirimi','Olayın ne olduğu ve açık konum bildirilmelidir.',['Rastgele bir adres verilmelidir.','Yalnız adımız söylenmelidir.','Bilgiler gizlenmelidir.']);return hQ(s+'. Görevli telefonda yönlendirme yaparsa ne yapılmalıdır?','🎧 Sakin iletişim','Sakin kalıp görevlinin yönlendirmeleri uygulanmalıdır.',['Telefon hemen kapatılmalıdır.','Görevli dinlenmemelidir.','Olay hakkında şaka yapılmalıdır.'])});
const sections=[
{code:'HB.2.2.1',color:'#e56b3f',soft:'#fff0e9',icon:'🥗',title:'Sağlıklı Büyüyelim',intro:'Beslenme, uyku, hareket ve kişisel bakım alışkanlıklarını değerlendir.',badge:'Sağlıklı Yaşam Rozeti',games:[{id:'saglik100',icon:'🌱',title:'Sağlıklı Büyüme Yolculuğu',desc:'100 farklı durumda sağlıklı seçimi yap.',q:health}]},
{code:'HB.2.2.2',color:'#7c4dcc',soft:'#f2ebff',icon:'🛡️',title:'Kişisel Alanımızı Koruyalım',intro:'Kişisel sınırlarını fark et, hayır de, uzaklaş ve yardım iste.',badge:'Kişisel Alan Rozeti',games:[{id:'alan100',icon:'✋',title:'Güvenli Alan Kalkanı',desc:'100 farklı durumda sınırlarını koru.',q:space}]},
{code:'HB.2.2.3',color:'#2578c4',soft:'#e7f3ff',icon:'🚦',title:'Trafik İşaret Levhaları',intro:'Temel trafik işaretlerini tanı ve güvenli davranışla ilişkilendir.',badge:'Trafik Dedektifi Rozeti',games:[{id:'trafik100',icon:'🪧',title:'Trafik İşareti Avı',desc:'100 trafik görevini tamamla.',q:traffic}]},
{code:'HB.2.2.4',color:'#d64c68',soft:'#ffeaf0',icon:'🚨',title:'Acil Durum Var',intro:'Acil durumu fark et, güvenliğini koru ve 112 ile doğru iletişim kur.',badge:'Acil Durum Rozeti',games:[{id:'acil100',icon:'📞',title:'112 Görev Merkezi',desc:'100 acil durum senaryosunda doğru adımı seç.',q:emergency}]}
];
let state=JSON.parse(localStorage.getItem("sg-progress")||'{"score":0,"wins":{}}');
const worlds=document.getElementById("worlds"),modal=document.getElementById("modal");
let game=null,qi=0,correct=0,locked=false;

function render(){
 worlds.innerHTML=sections.map((s,si)=>`<article class="world" style="--c:${s.color};--soft:${s.soft}">
 <div class="world-head"><div class="world-icon">${s.icon}</div><div><div class="code">${s.code}</div><h2>${si+1}. Bölüm · ${s.title}</h2><div>${s.badge} ${sectionWon(s)?"✅":"🔒"}</div></div></div>
 <div class="intro"><b>Konuyu keşfet</b>${s.intro}</div>
 <div class="cards">${s.games.map(g=>`<button class="card" data-id="${g.id}" style="--c:${s.color}"><span class="emoji">${g.icon}</span><h3>${g.title}</h3><p>${g.desc}</p><strong>${state.wins[g.id]?"Tamamlandı ✓":"Oyunu aç →"}</strong></button>`).join("")}</div></article>`).join("");
 document.querySelectorAll(".card").forEach(b=>b.onclick=()=>start(findGame(b.dataset.id)));
 updateProgress();
}
function findGame(id){for(const s of sections){const g=s.games.find(x=>x.id===id);if(g)return {...g,section:s}}}
function sectionWon(s){return s.games.every(g=>state.wins[g.id])}
function updateProgress(){document.getElementById("stars").textContent=state.score;document.getElementById("badges").textContent=sections.filter(sectionWon).length+"/4"}
function start(g){game={...g,q:[...g.q].sort(()=>Math.random()-.5)};qi=0;correct=0;locked=false;modal.hidden=false;document.body.style.overflow="hidden";showQ()}
function showQ(){
 const q=game.q[qi];locked=false;
 document.getElementById("gameHead").innerHTML=`<div class="game-title">${game.icon} ${game.title}</div><div class="game-meta">${game.section.code} · ${correct*10} puan</div>`;
 document.getElementById("bar").style.width=(qi/game.q.length*100)+"%";
 document.getElementById("question").innerHTML=`<div class="qno">GÖREV ${qi+1} / ${game.q.length}</div><div class="prompt">${q[0]}</div><div class="scene">${q[1]}</div>`;
 const opts=[...q[3]].sort(()=>Math.random()-.5);
 document.getElementById("answers").innerHTML=opts.map(a=>`<button class="answer">${a}</button>`).join("");
 document.getElementById("feedback").textContent="";document.getElementById("next").hidden=true;
 document.querySelectorAll(".answer").forEach(b=>b.onclick=()=>answer(b,q[2]));
}
function answer(btn,right){if(locked)return;locked=true;document.querySelectorAll(".answer").forEach(b=>{b.disabled=true;if(b.textContent===String(right))b.classList.add("good")});if(btn.textContent===String(right)){correct++;btn.classList.add("good");document.getElementById("feedback").textContent="Harika! Doğru cevap. +10 puan ⭐"}else{btn.classList.add("bad");document.getElementById("feedback").textContent="Birlikte öğrendik! Doğru cevap: "+right}document.getElementById("next").hidden=false}
document.getElementById("next").onclick=()=>{qi++;if(qi<game.q.length)showQ();else finish()};
function finish(){const won=correct>=80;if(won&&!state.wins[game.id]){state.wins[game.id]=true;state.score+=correct*10}else if(!state.wins[game.id])state.score+=correct*10;localStorage.setItem("sg-progress",JSON.stringify(state));document.getElementById("bar").style.width="100%";document.getElementById("question").innerHTML=`<div class="result"><div class="cup">${won?"🏆":"🌱"}</div><h2>${won?"Görev tamamlandı!":"Bir kez daha deneyelim!"}</h2><p>100 sorudan ${correct} tanesini doğru cevapladın. ${won?"Bu oyunun yıldızını kazandın!":"80 doğruya ulaştığında oyunu tamamlayacaksın."}</p><button class="play-again" id="again">${won?"Oyunlara dön":"Yeniden oyna"}</button></div>`;document.getElementById("answers").innerHTML="";document.getElementById("feedback").textContent="";document.getElementById("next").hidden=true;document.getElementById("again").onclick=()=>won?closeGame():start(game);render()}
function closeGame(){modal.hidden=true;document.body.style.overflow="";render()}
document.getElementById("close").onclick=closeGame;modal.onclick=e=>{if(e.target===modal)closeGame()};
document.getElementById("reset").onclick=()=>{if(confirm("Tüm puan ve rozetler sıfırlansın mı?")){state={score:0,wins:{}};localStorage.setItem("sg-progress",JSON.stringify(state));render()}};
render();